### ISSUE TITLE
General todo

### ISSUE THREAD

**Issue by erwinvaneyk** [erwinvaneyk/distributedrmi#2]
- [x] distributed logging (will be ported from DCS project)
- [x] inter-node communication (in the Connector)
- [ ] Separate baselogic from RMI (Maven modules)
- [ ] Add documentation
- [ ] Add performance-logging
- [ ] Add visualizer
